/**
 * Organic Traffic Breakthrough Mission (2026-08-21) — Phase 9 baseline.
 *
 * Persisted BEFORE evaluating whether the Phase 4 content changes (new
 * data/seo/alternative-guides.ts entries for todoist/setmore/clickup/
 * sprout-social/activecampaign; the new /recommend CTA on category and
 * comparison page templates) moved anything. Committed, not left in
 * var/ or /tmp, so a future session can do the actual before/after
 * comparison instead of re-deriving "what did this look like before."
 *
 * Source: the production seo-factory cron's cached run
 * (id: 2026-08-20T15-29-51-686Z-6d30c550, read via
 * lib/seo-factory/store.ts's readLatestSeoFactoryRun(), which reads
 * Vercel Blob — the same store the daily /api/cron/seo-factory job
 * writes to on Vercel's runtime, which has the real
 * GOOGLE_SEARCH_CONSOLE_SERVICE_ACCOUNT credential this local
 * environment does not: `vercel env pull` redacts it to the literal
 * string "[SENSITIVE]" for Sensitive-flagged env vars). This is
 * genuinely the freshest real GSC-backed data available without that
 * credential, generated by the same-day-cron pattern
 * (claimSeoFactoryRun de-dupes to one run per calendar day).
 *
 * GSC query window for these rows: 2026-07-21 to 2026-08-17 (the
 * factory run's own `window` field) — NOT the day this mission ran
 * (2026-08-21). This is real, honestly-labeled staleness (4 days), not
 * a live pull; do not treat it as same-day data in any future report.
 *
 * `opportunityScore` and `affiliateStatus` are the seo-factory's own
 * derived fields, reproduced here for context only — `affiliateStatus`
 * disagreed with the canonical ledger for setmore ("VIABLE" here vs.
 * ACTIVE in data/affiliate/canonical-ledger.ts, which is the real
 * source of truth) at the time this baseline was captured; noted, not
 * silently reconciled.
 */

export type TrafficMissionBaselineRow = {
  slug: string;
  query: string;
  targetUrl: string;
  impressions: number;
  clicks: number;
  ctr: number;
  position: number;
  intent: string;
  /** The seo-factory's own derived affiliateStatus at capture time — see module header re: the setmore discrepancy. */
  affiliateStatusAtCapture: string;
  opportunityScoreAtCapture: number;
};

export const TRAFFIC_MISSION_BASELINE = {
  capturedAt: "2026-08-21",
  sourceRunId: "2026-08-20T15-29-51-686Z-6d30c550",
  sourceRunGeneratedAt: "2026-08-20T15:29:51.686Z",
  gscWindow: { startDate: "2026-07-21", endDate: "2026-08-17" },
  scope: "Real Search Analytics rows for the 5 software pages whose /software/{slug} content was changed in this mission (new AlternativeDecisionGuide entries), pulled from the seo-factory's own cached opportunity list, not a fresh API call.",
  changedRoutes: [
    "/software/todoist",
    "/software/setmore",
    "/software/clickup",
    "/software/sprout-social",
    "/software/activecampaign",
  ],
  /** Every one of the 5 pages also gained a new inbound link to /recommend via the category-page and comparison-page CTA additions (Phase 6) — not GSC-measurable, tracked instead via the internal-link counts in the mission report. */
  rows: [
    { slug: "todoist", query: "todoist alternative", targetUrl: "/software/todoist", impressions: 70, clicks: 0, ctr: 0, position: 68.66, intent: "ALTERNATIVES", affiliateStatusAtCapture: "ACTIVE", opportunityScoreAtCapture: 77 },
    { slug: "clickup", query: "clickup alternatives", targetUrl: "/software/clickup", impressions: 219, clicks: 0, ctr: 0, position: 90.03, intent: "ALTERNATIVES", affiliateStatusAtCapture: "VIABLE", opportunityScoreAtCapture: 75 },
    { slug: "sprout-social", query: "sprout social alternatives", targetUrl: "/software/sprout-social", impressions: 208, clicks: 0, ctr: 0, position: 80.35, intent: "ALTERNATIVES", affiliateStatusAtCapture: "VIABLE", opportunityScoreAtCapture: 75 },
    { slug: "activecampaign", query: "activecampaign alternatives", targetUrl: "/software/activecampaign", impressions: 107, clicks: 0, ctr: 0, position: 76.93, intent: "ALTERNATIVES", affiliateStatusAtCapture: "VIABLE", opportunityScoreAtCapture: 74 },
    { slug: "setmore", query: "setmore alternatives", targetUrl: "/software/setmore", impressions: 35, clicks: 0, ctr: 0, position: 72.6, intent: "ALTERNATIVES", affiliateStatusAtCapture: "VIABLE", opportunityScoreAtCapture: 69 },
    { slug: "sprout-social", query: "social sprout alternatives", targetUrl: "/software/sprout-social", impressions: 87, clicks: 0, ctr: 0, position: 84.63, intent: "ALTERNATIVES", affiliateStatusAtCapture: "UNKNOWN", opportunityScoreAtCapture: 68 },
    { slug: "clickup", query: "clickup.com", targetUrl: "/software/clickup", impressions: 14, clicks: 0, ctr: 0, position: 67.14, intent: "FEATURE", affiliateStatusAtCapture: "VIABLE", opportunityScoreAtCapture: 67 },
    { slug: "setmore", query: "acuity scheduling vs setmore", targetUrl: "/software/setmore", impressions: 9, clicks: 0, ctr: 0, position: 78.56, intent: "COMPARISON", affiliateStatusAtCapture: "VIABLE", opportunityScoreAtCapture: 67 },
  ] satisfies TrafficMissionBaselineRow[],
  /** Site-wide context captured the same session, for framing scale — not per-route, do not compare directly against the rows above. */
  siteWideContext: {
    source: "seo-factory run comparisonDiagnosis field, same run as above",
    comparisonPagesWithAnyVisibility: 100,
    totalComparisonPages: 1123,
    comparisonImpressions28d: 565,
    comparisonClicks28d: 0,
    comparisonMedianPosition: 65.5,
  },
  /**
   * Never claim SEO success from this baseline alone (Phase 9's explicit
   * instruction). The next real check needs a fresh GSC pull — from the
   * Vercel runtime, not this local environment — for the SAME 8
   * query/page rows above, at least 2-3 weeks after this mission's
   * deployment (Google re-crawl and re-ranking is not instant), success
   * criteria would be REAL evidence of any of: average position moving
   * meaningfully below ~70 for these queries, non-zero clicks appearing,
   * or CTR moving above 0%. A same-day or same-week check would be
   * measuring noise, not signal.
   */
  reevaluationNotes:
    "Compare against a fresh pull of these exact 8 query+page rows no sooner than ~2-3 weeks after deployment (dpl id recorded in the mission's final report). Do not extrapolate from the biased/small samples in lib/agents/gsc-snapshot.ts's earlier snapshots -- pull a real, unbiased Search Analytics window for these specific pages/queries.",
};
