import type { AgentDefinition } from "@/types/agents";
import { wrapMaintenanceAgent } from "@/scripts/agents/wrappers/maintenance-wrapper";
import { executeLinksAgent } from "@/scripts/maintenance/links";
import { executeFreshnessAgent } from "@/scripts/maintenance/freshness";
import { executeSeoAgent } from "@/scripts/maintenance/seo";
import { executeRecommendationsAgent } from "@/scripts/maintenance/recommendations";
import { executeComparisonsAgent } from "@/scripts/maintenance/comparisons";
import { executeAffiliateAgent } from "@/scripts/maintenance/affiliate";
import { run as redirectBrokenUrlCheckRun } from "@/scripts/agents/seo/redirect-broken-url-check";
import { run as categoryCoverageDepthRun } from "@/scripts/agents/seo/category-coverage-depth";
import { run as duplicateDescriptionRun } from "@/scripts/agents/content/duplicate-description-detector";
import { run as templatedRepetitionRun } from "@/scripts/agents/content/templated-repetition-detector";
import { run as titleDescriptionQualityRun } from "@/scripts/agents/growth/title-description-quality";
import { run as internalLinkOpportunityRun } from "@/scripts/agents/growth/internal-link-opportunity";
import { run as cannibalizationDetectorRun } from "@/scripts/agents/growth/cannibalization-detector";
import { run as categoryOpportunityRun } from "@/scripts/agents/growth/category-opportunity";
import { run as freshnessRevenuePriorityRun } from "@/scripts/agents/growth/freshness-revenue-priority";
import { run as bestForPersonaOpportunityRun } from "@/scripts/agents/growth/best-for-persona-opportunity";
import { run as typescriptVerificationRun } from "@/scripts/agents/qa/typescript-verification";
import { run as lintVerificationRun } from "@/scripts/agents/qa/lint-verification";
import { run as dataValidationRun } from "@/scripts/agents/qa/data-validation";
import { run as buildVerificationRun } from "@/scripts/agents/qa/build-verification";
import {
  runHomepageSmoke,
  runSoftwareTemplateSmoke,
  runCategoryTemplateSmoke,
  runComparisonTemplateSmoke,
} from "@/scripts/agents/qa/template-smoke";
import { runSitemapLiveValidation, runRobotsLiveValidation } from "@/scripts/agents/qa/sitemap-robots-validation";
import { run as productionDeploymentSmokeRun } from "@/scripts/agents/qa/production-deployment-smoke";
import { run as criticalRouteAvailabilityRun } from "@/scripts/agents/qa/critical-route-availability";
import { run as ga4ConsentStaticCheckRun } from "@/scripts/agents/qa/ga4-consent-static-check";
import { run as ga4ConsentCodeAuditRun } from "@/scripts/agents/qa/ga4-consent-code-audit";
// Search Console agents (scripts/agents/seo/search-console-signals.ts,
// scripts/agents/{seo,growth}/search-console-*.ts) are genuinely
// implemented and unit-tested, but deliberately NOT imported here while
// `enabled: false` — the registry.test.ts invariant "disabled ⟹ run is
// null" means the orchestrator never even holds a reference to a blocked
// agent's run function, so it's structurally impossible for one to
// execute by accident. Import and wire in `run:` for each entry below
// only when flipping `enabled: true` with a real credential configured.
//
// seo-indexnow-submit is the one exception: it needs no credential (see
// its registry entry) and was live-verified end-to-end against the real
// IndexNow API (HTTP 202 "URL received") before enabling — so its run
// function IS imported and wired in below.
import { run as indexNowSubmitRun } from "@/scripts/agents/seo/indexnow-submit";

/**
 * The agent registry — the single source of truth for what the swarm can
 * run. Add a new agent by adding one entry here; see
 * docs/agents-architecture.md "How to add another agent" for the recipe.
 * Disable one by flipping `enabled: false` (keep the metadata — a disabled
 * entry documents a real, specified-but-blocked capability, which is the
 * point: never delete a blocked agent's spec, since the whole reason it's
 * blocked is recorded in `blockedReason`).
 */
export const AGENT_REGISTRY: AgentDefinition[] = [
  // ---------------------------------------------------------------------
  // Migrated (Phase 2): the six existing scripts/maintenance/*.ts agents,
  // wrapped as-is. See scripts/agents/wrappers/maintenance-wrapper.ts.
  // ---------------------------------------------------------------------
  {
    id: "maint-links",
    name: "Link Health Agent",
    domain: "qa",
    description: "Checks every live outbound URL in the dataset (official site, sources, vendor-resource links, active affiliate links) for reachability.",
    singleResponsibility: "Detect broken/unreachable outbound URLs.",
    inputs: ["data/software/*.json (website, sources, links.*)", "data/revenue/affiliate-programs.ts", "live HTTP requests to vendor URLs"],
    outputs: ["Finding[] (issue, per broken/degraded URL)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: [],
    permissions: ["read data/software", "read data/revenue", "outbound HTTP GET to vendor domains"],
    riskLevel: 0,
    costClass: "cheap",
    modelRequirement: "none",
    timeoutMs: 120_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Completes a bounded-concurrency check of every collected URL without throwing.",
    failureCriteria: "An unhandled exception during URL collection or checking.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: wrapMaintenanceAgent("maint-links", executeLinksAgent, { riskLevel: 1 }),
  },
  {
    id: "maint-freshness",
    name: "Data Freshness Agent",
    domain: "content",
    description: "Scores each software entry 0-100 on documentation recency/completeness (accessed_at age, optional-field presence, source count) — not factual accuracy.",
    singleResponsibility: "Flag software entries whose documentation is stale or thin.",
    inputs: ["data/software/*.json", "data/revenue/affiliate-programs.ts"],
    outputs: ["Finding[] (issue, per entry scoring below threshold)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: [],
    permissions: ["read data/software", "read data/revenue"],
    riskLevel: 0,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 30_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Scores every software entry without throwing.",
    failureCriteria: "An unhandled exception while scoring.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: wrapMaintenanceAgent("maint-freshness", executeFreshnessAgent, { riskLevel: 1 }),
  },
  {
    id: "maint-seo",
    name: "SEO Integrity Agent",
    domain: "seo",
    description: "Static checks against the real app/sitemap.ts and app/robots.ts output plus route source files: canonical presence, JSON-LD presence, sitemap/robots correctness, orphan-page risk, broken internal references, duplicate titles/descriptions.",
    singleResponsibility: "Catch structural SEO regressions in the codebase itself.",
    inputs: ["app/sitemap.ts", "app/robots.ts", "route source files (regex-checked)", "data/software, data/categories, data/comparisons"],
    outputs: ["Finding[] (issue)"],
    trigger: "scheduled",
    modes: ["daily", "weekly", "full"],
    dependencies: [],
    permissions: ["read app/ route files", "call sitemap()/robots() directly"],
    riskLevel: 0,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 30_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Completes all static checks without throwing.",
    failureCriteria: "A critical finding (escalates to run failure by design — these represent real code bugs) or an unhandled exception.",
    verificationAgent: "qa-sitemap-live-validation",
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: wrapMaintenanceAgent("maint-seo", executeSeoAgent, { riskLevel: 1 }),
  },
  {
    id: "maint-recommendations",
    name: "Recommendation Regression Agent",
    domain: "qa",
    description: "Runs 14 fixed fixtures against the real recommendation engine (lib/recommend/engine.ts) and checks structural assertions (winning category/slug, factor presence).",
    singleResponsibility: "Catch behavioral regressions in the recommendation engine.",
    inputs: ["lib/maintenance/recommendation-fixtures.ts", "lib/recommend/engine.ts (live call)"],
    outputs: ["Finding[] (issue, per failed fixture)"],
    trigger: "scheduled",
    modes: ["daily", "weekly", "full"],
    dependencies: [],
    permissions: ["call getRecommendations() directly"],
    riskLevel: 0,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 30_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "All 14 fixtures pass.",
    failureCriteria: "Any fixture assertion fails (escalates to run failure by design).",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: wrapMaintenanceAgent("maint-recommendations", executeRecommendationsAgent, { riskLevel: 1 }),
  },
  {
    id: "maint-comparisons",
    name: "Comparison Opportunity Agent",
    domain: "growth",
    description: "All-pairs scan for un-published /compare candidates with real relevance (direct-alternative or same-category) and enough data (3+ features each side), scored by a documented priority formula.",
    singleResponsibility: "Suggest new comparison-page candidates.",
    inputs: ["data/software/*.json", "data/comparisons.ts", "data/revenue/affiliate-programs.ts"],
    outputs: ["Finding[] (opportunity, per candidate pair)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: [],
    permissions: ["read data/software", "read data/comparisons", "read data/revenue"],
    riskLevel: 2,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 30_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Completes the all-pairs scan without throwing.",
    failureCriteria: "An unhandled exception during the scan.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: wrapMaintenanceAgent("maint-comparisons", executeComparisonsAgent, { opportunityKind: true, riskLevel: 2 }),
  },
  {
    id: "maint-affiliate",
    name: "Affiliate Opportunity Agent",
    domain: "growth",
    description: "Cross-references revenue tier against affiliate-program activation status across four lenses (confirmed-not-activated, unresolved, high-tier-no-program, stale-research).",
    singleResponsibility: "Surface affiliate-program follow-up opportunities.",
    inputs: ["data/software/*.json", "data/revenue/affiliate-programs.ts", "config/affiliate-credentials.json (existence check only, never contents)"],
    outputs: ["Finding[] (opportunity)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: [],
    permissions: ["read data/software", "read data/revenue", "read config/affiliate-credentials.json existence (not contents)"],
    riskLevel: 1,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 30_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Completes all four lenses without throwing.",
    failureCriteria: "An unhandled exception.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: wrapMaintenanceAgent("maint-affiliate", executeAffiliateAgent, { opportunityKind: true, riskLevel: 1 }),
  },

  // ---------------------------------------------------------------------
  // New SEO agents (Phase 3/4)
  // ---------------------------------------------------------------------
  {
    id: "seo-redirect-broken-url-check",
    name: "Redirect/Broken URL Checker (own pages)",
    domain: "seo",
    description: "Live HTTP checks a stable, deterministic sample of Miloosh's own rendered pages (every category, every static/legal page, a sample of software and comparison pages) for non-200 responses.",
    singleResponsibility: "Catch broken or unexpectedly-redirecting internal routes on the live site.",
    inputs: ["data/software, data/categories, data/comparisons (to build the URL list)", "live HTTP GET to SITE_URL"],
    outputs: ["Finding[] (issue)"],
    trigger: "scheduled",
    modes: ["daily", "weekly", "full"],
    dependencies: [],
    permissions: ["outbound HTTP GET to this site's own domain"],
    riskLevel: 0,
    costClass: "cheap",
    modelRequirement: "none",
    timeoutMs: 60_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Completes checking the sampled URL set without throwing.",
    failureCriteria: "An unhandled exception during the check.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: redirectBrokenUrlCheckRun,
  },
  {
    id: "seo-category-coverage-depth",
    name: "Category Coverage Depth",
    domain: "seo",
    description: "Flags indexable-but-thin categories (1-3 software entries) as a content-depth opportunity, distinct from validate-data's build-blocking true-orphan (0 entries) check.",
    singleResponsibility: "Identify categories too thin to be a strong landing page.",
    inputs: ["data/software/*.json", "data/categories"],
    outputs: ["Finding[] (opportunity)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: [],
    permissions: ["read data/software", "read data/categories"],
    riskLevel: 2,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 10_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Counts every category without throwing.",
    failureCriteria: "An unhandled exception.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: categoryCoverageDepthRun,
  },
  {
    id: "seo-search-console-signals",
    name: "Search Console Signals (URL Inspection / index visibility)",
    domain: "seo",
    description: "Pulls real DISCOVERED/CRAWLED/INDEXED state per sampled URL from Google's URL Inspection API. Genuinely implemented (JWT service-account auth + REST client, unit-tested with real cryptographic signature verification — see tests/agents/google-search-console.test.ts) — blocked only on a real credential, not on missing code.",
    singleResponsibility: "Feed real per-URL indexing state into the swarm — DISCOVERED/CRAWLED/INDEXED are different states from 'in the sitemap.'",
    inputs: ["Google Search Console URL Inspection API (real client: scripts/agents/seo/lib/google-search-console-client.ts)"],
    outputs: ["Finding[] (issue, per URL not confirmed indexed)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: [],
    permissions: ["Search Console API read access (not configured — needs GOOGLE_SEARCH_CONSOLE_SERVICE_ACCOUNT + GOOGLE_SEARCH_CONSOLE_PROPERTY)"],
    riskLevel: 0,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 60_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Every sampled URL inspected without throwing.",
    failureCriteria: "An unhandled exception (including a real auth/API failure).",
    verificationAgent: null,
    enabled: false,
    blockedReason: "Adapter is real and unit-tested; needs a real Google Cloud service-account credential (GOOGLE_SEARCH_CONSOLE_SERVICE_ACCOUNT) added as a user on the Search Console property (GOOGLE_SEARCH_CONSOLE_PROPERTY) — owner action, not a code gap.",
    version: "0.2.0-blocked",
    run: null,
  },
  {
    id: "seo-indexnow-submit",
    name: "IndexNow Submission",
    domain: "seo",
    description: "Submits real, new-since-last-run URLs to the IndexNow API (api.indexnow.org), which needs no account or signup — the key (public/64571916632587e2f714c221fb8ccc42.txt) is self-issued and hosted at the domain root. Never resubmits a URL already recorded as submitted (var/agents/state.json indexNowSubmittedAt) — Section C's explicit 'do not repeatedly submit unchanged URLs' rule.",
    singleResponsibility: "Notify IndexNow-participating search engines (Bing, Yandex, Seznam.cz, Naver — not Google, which doesn't participate) of new URLs.",
    inputs: ["data/software, data/categories, data/comparisons (to build the current URL list)", "var/agents/state.json (previously-submitted URLs)"],
    outputs: ["Finding[] (issue, only on a failed submission) — the submission itself is the primary output, not a Finding"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: [],
    permissions: ["outbound HTTPS POST to api.indexnow.org (real external write — see file header for why this is Level 1, not Level 4)"],
    riskLevel: 1,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 30_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "IndexNow returns HTTP 200 or 202 for the submitted batch.",
    failureCriteria: "IndexNow returns a non-2xx status, or the request throws.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: indexNowSubmitRun,
  },
  {
    id: "seo-bing-webmaster-signals",
    name: "Bing Webmaster Signals",
    domain: "seo",
    description: "Pulls real Bing query performance (clicks, impressions, position) via the Bing Webmaster Tools API — simple API-key auth (no OAuth/JWT), verified against current Microsoft documentation. Genuinely implemented and unit-tested (scripts/agents/seo/lib/bing-webmaster-client.ts) — blocked only on a real API key.",
    singleResponsibility: "Feed real Bing-side query performance into the swarm, cross-checkable against the Google Search Console CTR agent.",
    inputs: ["Bing Webmaster Tools API GetQueryStats (not configured)"],
    outputs: ["Finding[] (opportunity)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: [],
    permissions: ["Bing Webmaster Tools API read access (not configured — needs BING_WEBMASTER_API_KEY + BING_WEBMASTER_SITE_URL)"],
    riskLevel: 0,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 30_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Queries and analyzes real Bing query stats without throwing.",
    failureCriteria: "An unhandled exception (including a real auth/API failure).",
    verificationAgent: null,
    enabled: false,
    blockedReason: "Adapter is real and unit-tested; needs an owner to verify the site in Bing Webmaster Tools (often a one-click import from an already-verified Google Search Console property) and generate an API key from Settings → API Access — owner action, not a code gap.",
    version: "0.2.0-blocked",
    run: null,
  },

  // ---------------------------------------------------------------------
  // New content-intelligence agents (Phase 3/4)
  // ---------------------------------------------------------------------
  {
    id: "content-duplicate-description-detector",
    name: "Duplicate Description Detector",
    domain: "content",
    description: "Detects exact and near-duplicate (Jaccard word-overlap ≥75%) catalog `description` fields across software entries — the body copy, not the generated meta description (already covered by maint-seo).",
    singleResponsibility: "Catch duplicated or interchangeable body-copy descriptions.",
    inputs: ["data/software/*.json (description field)"],
    outputs: ["Finding[] (issue)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: [],
    permissions: ["read data/software"],
    riskLevel: 1,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 15_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Completes the O(n^2) comparison without throwing.",
    failureCriteria: "An unhandled exception.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: duplicateDescriptionRun,
  },
  {
    id: "content-templated-repetition-detector",
    name: "Templated Repetition Detector",
    domain: "content",
    description: "Flags exact phrases reused verbatim in bestFor/pros/cons across 5+ different products — a sign of templated, low-effort content rather than per-product research.",
    singleResponsibility: "Catch boilerplate phrasing masquerading as product-specific claims.",
    inputs: ["data/software/*.json (bestFor, pros, cons)"],
    outputs: ["Finding[] (issue)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: [],
    permissions: ["read data/software"],
    riskLevel: 1,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 15_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Completes the scan without throwing.",
    failureCriteria: "An unhandled exception.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: templatedRepetitionRun,
  },

  // ---------------------------------------------------------------------
  // New growth/marketing agents (Phase 4) — real, data-derived
  // ---------------------------------------------------------------------
  {
    id: "growth-title-description-quality",
    name: "Title/Description Quality",
    domain: "growth",
    description: "Checks the real generateMetaDescription/generateComparisonMetaDescription output for truncation (cut off mid-sentence) or thinness. Reports one systemic finding when truncation affects 20%+ of a page type (a template problem) rather than one near-duplicate finding per page.",
    singleResponsibility: "Catch clipped or thin generated meta descriptions.",
    inputs: ["lib/generators.ts, lib/comparison.ts (live calls)", "data/software, data/comparisons"],
    outputs: ["Finding[] (opportunity)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: [],
    permissions: ["read data/software", "read data/comparisons", "call generator functions"],
    riskLevel: 2,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 15_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Completes the scan without throwing.",
    failureCriteria: "An unhandled exception.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: titleDescriptionQualityRun,
  },
  {
    id: "growth-internal-link-opportunity",
    name: "Internal Link Opportunity",
    domain: "growth",
    description: "Computes a real inbound-internal-link count per software page (category link + comparisons + alternatives-mentions + related-software appearances) and flags Tier A/B revenue products that are under-linked.",
    singleResponsibility: "Prioritize which pages most need more internal links, by business value.",
    inputs: ["data/software (alternatives, category)", "data/comparisons", "lib/related.ts (getRelatedSoftware)", "lib/revenue/scoring.ts"],
    outputs: ["Finding[] (opportunity)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: [],
    permissions: ["read data/software", "read data/comparisons", "read data/revenue"],
    riskLevel: 2,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 15_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Computes inbound counts for every software page without throwing.",
    failureCriteria: "An unhandled exception.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: internalLinkOpportunityRun,
  },
  {
    id: "growth-cannibalization-detector",
    name: "Cannibalization Detector",
    domain: "growth",
    description: "Flags same-category product pairs whose bestFor framing overlaps ≥60% — a real risk of two Miloosh pages competing for the same search intent instead of each owning a distinct angle.",
    singleResponsibility: "Detect same-category pages targeting overlapping buyer intent.",
    inputs: ["data/software (bestFor, category)"],
    outputs: ["Finding[] (opportunity)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: [],
    permissions: ["read data/software"],
    riskLevel: 2,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 15_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Completes the within-category comparison without throwing.",
    failureCriteria: "An unhandled exception.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: cannibalizationDetectorRun,
  },
  {
    id: "growth-category-opportunity",
    name: "Category Opportunity",
    domain: "growth",
    description: "Frequency-analyzes the real `tags` field for cross-category clusters of 8+ products not matching any existing category — a data-backed signal for a possible new category/filter/roundup.",
    singleResponsibility: "Surface tag clusters that outgrow the current category taxonomy.",
    inputs: ["data/software (tags, category)", "data/categories"],
    outputs: ["Finding[] (opportunity)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: [],
    permissions: ["read data/software", "read data/categories"],
    riskLevel: 3,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 15_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Completes the tag frequency scan without throwing.",
    failureCriteria: "An unhandled exception.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: categoryOpportunityRun,
  },
  {
    id: "growth-freshness-revenue-priority",
    name: "Freshness × Revenue Priority",
    domain: "growth",
    description: "Cross-references maint-freshness's documentation-recency score with lib/revenue/scoring.ts's revenue tier to rank which stale entries are worth re-researching first.",
    singleResponsibility: "Triage stale documentation by business value, not just age.",
    inputs: ["scripts/maintenance/freshness.ts (scoreSoftware, reused directly)", "lib/revenue/scoring.ts"],
    outputs: ["Finding[] (opportunity)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: ["maint-freshness"],
    permissions: ["read data/software", "read data/revenue"],
    riskLevel: 1,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 15_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Completes scoring for every software entry without throwing.",
    failureCriteria: "An unhandled exception.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: freshnessRevenuePriorityRun,
  },
  {
    id: "growth-best-for-persona-opportunity",
    name: "\"Best X for Y\" Persona Opportunity",
    domain: "growth",
    description: "Scans real bestFor text for a fixed persona-keyword list, clustered by category — flags categories with 4+ products already explicitly serving the same persona as a themed-roundup content opportunity. Discovery only; no /best route exists to publish to.",
    singleResponsibility: "Surface persona-based content-format opportunities backed by existing editorial text.",
    inputs: ["data/software (bestFor, category)", "data/categories"],
    outputs: ["Finding[] (opportunity)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: [],
    permissions: ["read data/software", "read data/categories"],
    riskLevel: 3,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 15_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Completes the persona-keyword scan without throwing.",
    failureCriteria: "An unhandled exception.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: bestForPersonaOpportunityRun,
  },

  // ---------------------------------------------------------------------
  // Blocked growth agents — real, specified, not runnable in this
  // environment. See each agent's adapter file for exactly what's missing.
  // ---------------------------------------------------------------------
  {
    id: "growth-search-demand-discovery",
    name: "Search-Demand Discovery",
    domain: "growth",
    description: "Would identify high-volume, low-competition queries relevant to the catalog using real keyword-volume data.",
    singleResponsibility: "Discover real search-demand signal for new content targets.",
    inputs: ["Keyword-volume API (not configured)"],
    outputs: ["Finding[] (opportunity)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: [],
    permissions: ["Keyword-volume API read access (not configured)"],
    riskLevel: 0,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 30_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "N/A — blocked.",
    failureCriteria: "N/A — blocked.",
    verificationAgent: null,
    enabled: false,
    blockedReason: "No keyword-volume API credentials configured. See scripts/agents/growth/keyword-demand-adapter.ts.",
    version: "0.1.0-blocked",
    run: null,
  },
  {
    id: "growth-longtail-query-discovery",
    name: "Long-Tail Query Discovery",
    domain: "growth",
    description: "Would mine Search Console query data for real long-tail queries the site already gets impressions for but doesn't have dedicated content for.",
    singleResponsibility: "Discover real long-tail query opportunities.",
    inputs: ["Search Console Search Analytics API (not configured)"],
    outputs: ["Finding[] (opportunity)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: ["seo-search-console-signals"],
    permissions: ["Search Console API read access (not configured)"],
    riskLevel: 0,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 30_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "N/A — blocked.",
    failureCriteria: "N/A — blocked.",
    verificationAgent: null,
    enabled: false,
    blockedReason: "Depends on seo-search-console-signals, which is itself blocked (no GSC credentials configured).",
    version: "0.1.0-blocked",
    run: null,
  },
  {
    id: "growth-commercial-intent-keyword-discovery",
    name: "Commercial-Intent Keyword Discovery",
    domain: "growth",
    description: "Would identify keyword variants with real commercial/buying intent (\"pricing\", \"vs\", \"alternative\", \"best\") using real keyword-volume + intent classification data.",
    singleResponsibility: "Discover real commercial-intent keyword opportunities.",
    inputs: ["Keyword-volume API (not configured)"],
    outputs: ["Finding[] (opportunity)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: [],
    permissions: ["Keyword-volume API read access (not configured)"],
    riskLevel: 0,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 30_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "N/A — blocked.",
    failureCriteria: "N/A — blocked.",
    verificationAgent: null,
    enabled: false,
    blockedReason: "No keyword-volume API credentials configured. See scripts/agents/growth/keyword-demand-adapter.ts.",
    version: "0.1.0-blocked",
    run: null,
  },
  {
    id: "growth-emerging-tool-discovery",
    name: "Emerging Tool Discovery",
    domain: "growth",
    description: "Would monitor software-launch feeds/directories for new tools worth adding to the catalog.",
    singleResponsibility: "Discover new software products worth researching and adding.",
    inputs: ["External web monitoring (not configured for automated runs)"],
    outputs: ["Finding[] (opportunity)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: [],
    permissions: ["External web fetch (not configured for automated runs)"],
    riskLevel: 0,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 30_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "N/A — blocked.",
    failureCriteria: "N/A — blocked.",
    verificationAgent: null,
    enabled: false,
    blockedReason: "No automated external web monitoring configured. See scripts/agents/growth/external-monitoring-adapter.ts — interactive WebSearch is available for one-off human-directed research, but not for this scheduled agent.",
    version: "0.1.0-blocked",
    run: null,
  },
  {
    id: "growth-competitor-gap-discovery",
    name: "Competitor Comparison-Gap Discovery",
    domain: "growth",
    description: "Would crawl competitor comparison sites to find comparison pairs they cover that Miloosh doesn't.",
    singleResponsibility: "Discover comparison-page gaps relative to competitors.",
    inputs: ["External web monitoring (not configured for automated runs)"],
    outputs: ["Finding[] (opportunity)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: [],
    permissions: ["External web fetch (not configured for automated runs)"],
    riskLevel: 0,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 30_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "N/A — blocked.",
    failureCriteria: "N/A — blocked.",
    verificationAgent: null,
    enabled: false,
    blockedReason: "No automated external web monitoring configured. See scripts/agents/growth/external-monitoring-adapter.ts.",
    version: "0.1.0-blocked",
    run: null,
  },
  {
    id: "growth-distribution-opportunity-discovery",
    name: "Distribution Opportunity Discovery",
    domain: "growth",
    description: "Would identify legitimate directories/communities where Miloosh could be listed (never automated posting — discovery only, publication requires human authorization per the brief).",
    singleResponsibility: "Discover legitimate distribution/listing opportunities.",
    inputs: ["External web monitoring (not configured for automated runs)"],
    outputs: ["Finding[] (opportunity, discovery only — never auto-published)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: [],
    permissions: ["External web fetch (not configured for automated runs)"],
    riskLevel: 1,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 30_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "N/A — blocked.",
    failureCriteria: "N/A — blocked.",
    verificationAgent: null,
    enabled: false,
    blockedReason: "No automated external web monitoring configured. See scripts/agents/growth/external-monitoring-adapter.ts.",
    version: "0.1.0-blocked",
    run: null,
  },
  {
    id: "growth-backlink-opportunity-discovery",
    name: "Backlink Opportunity Discovery",
    domain: "growth",
    description: "Would identify real backlink opportunities using backlink-data-provider signals (discovery only — never automated outreach).",
    singleResponsibility: "Discover legitimate backlink opportunities.",
    inputs: ["Backlink-data API (not configured)"],
    outputs: ["Finding[] (opportunity, discovery only — never auto-published/sent)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: [],
    permissions: ["Backlink-data API read access (not configured)"],
    riskLevel: 1,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 30_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "N/A — blocked.",
    failureCriteria: "N/A — blocked.",
    verificationAgent: null,
    enabled: false,
    blockedReason: "No backlink-data API credentials configured. See scripts/agents/growth/backlink-adapter.ts.",
    version: "0.1.0-blocked",
    run: null,
  },
  {
    id: "growth-search-console-ctr-opportunity",
    name: "High-Impression / Low-CTR Opportunity",
    domain: "growth",
    description: "Flags pages with real Search Console impressions and a decent average position but a low click-through rate — a title/description rewrite opportunity backed by actual query data. Scoring logic genuinely implemented and unit-tested (tests/agents/search-console-agents.test.ts) — blocked only on the same missing credential as seo-search-console-signals.",
    singleResponsibility: "Detect real impression-vs-click gaps worth a title/description rewrite.",
    inputs: ["Search Console Search Analytics API, dimension=page (not configured)"],
    outputs: ["Finding[] (opportunity)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: ["seo-search-console-signals"],
    permissions: ["Search Console API read access (not configured)"],
    riskLevel: 2,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 60_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Queries and analyzes real page-level performance without throwing.",
    failureCriteria: "An unhandled exception (including a real auth/API failure).",
    verificationAgent: null,
    enabled: false,
    blockedReason: "Same missing credential as seo-search-console-signals (GOOGLE_SEARCH_CONSOLE_SERVICE_ACCOUNT / GOOGLE_SEARCH_CONSOLE_PROPERTY) — not a code gap.",
    version: "0.2.0-blocked",
    run: null,
  },
  {
    id: "seo-search-console-ranking-movement",
    name: "Ranking Movement",
    domain: "seo",
    description: "Compares real average position per query between two adjacent time windows (no historical state needed) and flags significant drops/gains. Genuinely implemented and unit-tested.",
    singleResponsibility: "Detect real, significant ranking movement per query.",
    inputs: ["Search Console Search Analytics API, dimension=query, two date windows (not configured)"],
    outputs: ["Finding[] (regression for drops, opportunity for gains)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: ["seo-search-console-signals"],
    permissions: ["Search Console API read access (not configured)"],
    riskLevel: 1,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 60_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Queries and compares both windows without throwing.",
    failureCriteria: "An unhandled exception (including a real auth/API failure).",
    verificationAgent: null,
    enabled: false,
    blockedReason: "Same missing credential as seo-search-console-signals — not a code gap.",
    version: "0.1.0-blocked",
    run: null,
  },
  {
    id: "growth-search-console-winner-loser",
    name: "Growth Winner / Loser",
    domain: "growth",
    description: "Compares real click counts per page between two adjacent time windows and flags significant gainers/losers — the actual traffic outcome, distinct from ranking-movement's position-per-query view. Genuinely implemented and unit-tested.",
    singleResponsibility: "Detect real, significant traffic movement per page.",
    inputs: ["Search Console Search Analytics API, dimension=page, two date windows (not configured)"],
    outputs: ["Finding[] (opportunity for winners, regression for losers)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: ["seo-search-console-signals"],
    permissions: ["Search Console API read access (not configured)"],
    riskLevel: 1,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 60_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Queries and compares both windows without throwing.",
    failureCriteria: "An unhandled exception (including a real auth/API failure).",
    verificationAgent: null,
    enabled: false,
    blockedReason: "Same missing credential as seo-search-console-signals — not a code gap.",
    version: "0.1.0-blocked",
    run: null,
  },
  {
    id: "growth-search-console-content-opportunity",
    name: "Content Opportunity (Search Console-backed)",
    domain: "growth",
    description: "Flags real queries with meaningful impressions but too weak a position to compete — evidence that no existing page serves that query well. The most evidence-backed 'write about X' signal this system can produce, since X is a real query real searchers already used. Genuinely implemented and unit-tested.",
    singleResponsibility: "Detect real content gaps backed by actual query impressions.",
    inputs: ["Search Console Search Analytics API, dimension=query (not configured)"],
    outputs: ["Finding[] (opportunity)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: ["seo-search-console-signals"],
    permissions: ["Search Console API read access (not configured)"],
    riskLevel: 3,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 60_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Queries and analyzes real query performance without throwing.",
    failureCriteria: "An unhandled exception (including a real auth/API failure).",
    verificationAgent: null,
    enabled: false,
    blockedReason: "Same missing credential as seo-search-console-signals — not a code gap.",
    version: "0.1.0-blocked",
    run: null,
  },

  // ---------------------------------------------------------------------
  // Indexation-analysis workflow (Phase 3 priority #1) — items C, F, G, I,
  // J of the brief's A-J list. B (template distribution) and D/E/H
  // (internal-link / content-similarity / search-demand) are dimensions
  // computed inside these agents by reusing existing utilities, not
  // separate scheduled agents — see docs/agents-architecture.md.
  // ---------------------------------------------------------------------
  {
    id: "seo-indexed-vs-nonindexed-comparator",
    name: "Indexed vs. Non-Indexed Comparator",
    domain: "seo",
    description: "The centerpiece of the indexation-analysis workflow: samples ~50 URLs biased toward capturing both indexed and crawled-not-indexed pages (a naive random sample would very likely miss the indexed group entirely at the current ~2.8% indexed rate), then compares the two groups across internal-link count, content length, freshness, content similarity, template type, and Search Console impressions/clicks. Every finding is evidence-graded (OBSERVATION/HYPOTHESIS/CONFIDENCE/PROPOSED TEST) — never asserts causation from a correlation.",
    singleResponsibility: "Find measurable, evidence-graded differences between indexed and crawled-not-indexed pages.",
    inputs: [
      "Google Search Console URL Inspection API (not configured)",
      "Google Search Console Search Analytics API, dimension=page (not configured)",
      "data/software (via growth-internal-link-opportunity's computeInboundCounts, content-similarity via shared text-similarity util)",
      "scripts/maintenance/freshness.ts (scoreSoftware)",
      "lib/revenue/scoring.ts (tier, used only as a labeled business-priority signal, never as an SEO cause)",
    ],
    outputs: ["Finding[] (issue/info, evidence-graded)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: ["seo-search-console-signals"],
    permissions: ["Search Console API read access (not configured)"],
    riskLevel: 2,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 120_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Builds profiles for the sample and compares groups without throwing; correctly reports 'no comparison' if one group is empty rather than fabricating one.",
    failureCriteria: "An unhandled exception (including a real auth/API failure).",
    verificationAgent: null,
    enabled: false,
    blockedReason: "Same missing credential as seo-search-console-signals — not a code gap. Fully implemented and unit-tested (tests/agents/indexed-vs-nonindexed-comparator.test.ts) with synthetic profiles.",
    version: "1.0.0-blocked",
    run: null,
  },
  {
    id: "seo-canonical-consistency-analyzer",
    name: "Canonical Consistency Analyzer",
    domain: "seo",
    description: "Item F: compares each sampled URL's declared canonical against its own URL (every Miloosh page is expected to canonicalize to itself) and against Google's own selected canonical (googleCanonical) — a mismatch on either axis is a real, checkable technical fact, not a hypothesis.",
    singleResponsibility: "Detect canonical-tag mismatches using real URL Inspection data.",
    inputs: ["Google Search Console URL Inspection API (not configured)"],
    outputs: ["Finding[] (issue/regression)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: ["seo-search-console-signals"],
    permissions: ["Search Console API read access (not configured)"],
    riskLevel: 1,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 60_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Checks canonical consistency for every inspected URL without throwing.",
    failureCriteria: "An unhandled exception (including a real auth/API failure).",
    verificationAgent: null,
    enabled: false,
    blockedReason: "Same missing credential as seo-search-console-signals — not a code gap. Fully implemented and unit-tested.",
    version: "1.0.0-blocked",
    run: null,
  },
  {
    id: "seo-crawl-recency-analyzer",
    name: "Crawl Recency Analyzer",
    domain: "seo",
    description: "Item G: among crawled-but-not-indexed pages specifically, flags real robots.txt blocks and failed fetches (critical, technical facts) and stale crawl timestamps (info — Google hasn't seen recent changes yet).",
    singleResponsibility: "Detect stale, blocked, or failed crawls among non-indexed pages using real URL Inspection data.",
    inputs: ["Google Search Console URL Inspection API (not configured)"],
    outputs: ["Finding[] (issue)"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: ["seo-search-console-signals"],
    permissions: ["Search Console API read access (not configured)"],
    riskLevel: 1,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 60_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Checks crawl recency/fetch/robots state for every inspected URL without throwing.",
    failureCriteria: "An unhandled exception (including a real auth/API failure).",
    verificationAgent: null,
    enabled: false,
    blockedReason: "Same missing credential as seo-search-console-signals — not a code gap. Fully implemented and unit-tested.",
    version: "1.0.0-blocked",
    run: null,
  },
  {
    id: "seo-priority-candidate-selector",
    name: "Priority Candidate Selector",
    domain: "seo",
    description: "Item I: selects 5-20 real, specific crawled-not-indexed URLs for a minimal reversible experiment, scored by evidenced weaknesses (low inbound links, high content similarity, low freshness, stale crawl) with revenue tier used ONLY as a tiebreaker among equally-evidenced candidates, never as a standalone reason. Never selects a URL with zero evidenced weaknesses just to hit a quota. Records every selection in lib/agents/experiment-tracker.ts for seo-experiment-verifier to check back on.",
    singleResponsibility: "Pick a small, evidence-based batch of URLs worth an indexation experiment.",
    inputs: ["Google Search Console URL Inspection API (not configured)", "the same reused D/E/freshness/revenue-tier signals as the comparator"],
    outputs: ["Finding[] (opportunity, one per selected candidate)", "lib/agents/experiment-tracker.ts entries"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: ["seo-search-console-signals"],
    permissions: ["Search Console API read access (not configured)", "write to var/agents/experiment-candidates.json (local file, not external)"],
    riskLevel: 2,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 60_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Selects and records 0-20 evidenced candidates without throwing.",
    failureCriteria: "An unhandled exception (including a real auth/API failure).",
    verificationAgent: "seo-experiment-verifier",
    enabled: false,
    blockedReason: "Same missing credential as seo-search-console-signals — not a code gap. Fully implemented and unit-tested (tests/agents/priority-candidate-selector.test.ts).",
    version: "1.0.0-blocked",
    run: null,
  },
  {
    id: "seo-experiment-verifier",
    name: "Experiment Verifier",
    domain: "seo",
    description: "Item J: closes the loop item I opens. Re-inspects any experiment candidate at least 14 days after selection and reports whether its verdict/coverageState actually changed — a measured fact, explicitly never claimed as proof the experiment caused it (Google's crawl schedule moves independently). Implements 'track whether indexing changes later' as a real, running mechanism via lib/agents/experiment-tracker.ts.",
    singleResponsibility: "Report whether previously-selected experiment candidates' indexing state has changed.",
    inputs: ["lib/agents/experiment-tracker.ts (candidates ready for re-check)", "Google Search Console URL Inspection API (not configured)"],
    outputs: ["Finding[] (info/regression)", "lib/agents/experiment-tracker.ts outcome updates"],
    trigger: "scheduled",
    modes: ["weekly", "full"],
    dependencies: ["seo-search-console-signals", "seo-priority-candidate-selector"],
    permissions: ["Search Console API read access (not configured)", "read/write var/agents/experiment-candidates.json (local file, not external)"],
    riskLevel: 0,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 60_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Re-inspects every ready candidate and records an outcome without throwing.",
    failureCriteria: "An unhandled exception (including a real auth/API failure).",
    verificationAgent: null,
    enabled: false,
    blockedReason: "Same missing credential as seo-search-console-signals — not a code gap. Fully implemented and unit-tested (tests/agents/experiment-tracker.test.ts).",
    version: "1.0.0-blocked",
    run: null,
  },

  // ---------------------------------------------------------------------
  // QA / Monitoring swarm (Phase 3) — "many small checkers," each
  // independently runnable, consolidated by the orchestrator into a
  // single PASS/WARN/FAIL per check plus an overall qaOverall verdict.
  // ---------------------------------------------------------------------
  {
    id: "qa-typescript-verification",
    name: "TypeScript Verification",
    domain: "qa",
    description: "Wraps `npx tsc --noEmit`. Never reimplements type checking.",
    singleResponsibility: "Confirm the codebase typechecks cleanly.",
    inputs: ["entire TypeScript source tree, tsconfig.json"],
    outputs: ["Finding[] (issue) on failure only"],
    trigger: "scheduled",
    modes: ["quick", "daily", "weekly", "full"],
    dependencies: [],
    permissions: ["execute `npx tsc --noEmit`"],
    riskLevel: 0,
    costClass: "cheap",
    modelRequirement: "none",
    timeoutMs: 60_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Exit code 0.",
    failureCriteria: "Non-zero exit code.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: typescriptVerificationRun,
  },
  {
    id: "qa-lint-verification",
    name: "Lint Verification",
    domain: "qa",
    description: "Wraps `npm run lint` (ESLint). Never reimplements lint rules.",
    singleResponsibility: "Confirm the codebase passes lint cleanly.",
    inputs: ["entire source tree, eslint.config.mjs"],
    outputs: ["Finding[] (issue) on failure only"],
    trigger: "scheduled",
    modes: ["quick", "daily", "weekly", "full"],
    dependencies: [],
    permissions: ["execute `npm run lint`"],
    riskLevel: 0,
    costClass: "cheap",
    modelRequirement: "none",
    timeoutMs: 60_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Exit code 0.",
    failureCriteria: "Non-zero exit code.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: lintVerificationRun,
  },
  {
    id: "qa-data-validation",
    name: "Data Validation",
    domain: "qa",
    description: "Wraps `npm run validate:data` (scripts/validate-data.ts). Never reimplements the checks.",
    singleResponsibility: "Confirm data/software, data/categories, data/comparisons pass validation.",
    inputs: ["data/software, data/categories, data/comparisons"],
    outputs: ["Finding[] (issue) on failure only"],
    trigger: "scheduled",
    modes: ["quick", "daily", "weekly", "full"],
    dependencies: [],
    permissions: ["execute `npm run validate:data`"],
    riskLevel: 0,
    costClass: "cheap",
    modelRequirement: "none",
    timeoutMs: 60_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Exit code 0.",
    failureCriteria: "Non-zero exit code.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: dataValidationRun,
  },
  {
    id: "qa-build-verification",
    name: "Build Verification",
    domain: "qa",
    description: "Wraps `npm run build` (full Next.js production build, ~1400 static pages). Slow — excluded from QUICK mode.",
    singleResponsibility: "Confirm the codebase produces a clean production build.",
    inputs: ["entire source tree"],
    outputs: ["Finding[] (issue) on failure only"],
    trigger: "scheduled",
    modes: ["daily", "weekly", "full"],
    dependencies: ["qa-typescript-verification", "qa-data-validation"],
    permissions: ["execute `npm run build`"],
    riskLevel: 0,
    costClass: "moderate",
    modelRequirement: "none",
    timeoutMs: 300_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "Exit code 0.",
    failureCriteria: "Non-zero exit code.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: buildVerificationRun,
  },
  {
    id: "qa-homepage-smoke",
    name: "Homepage Smoke Check",
    domain: "qa",
    description: "Live-fetches the homepage and asserts 200 + expected content markers.",
    singleResponsibility: "Confirm the homepage template renders correctly in production.",
    inputs: ["live HTTP GET to SITE_URL"],
    outputs: ["Finding[] (issue) on failure only"],
    trigger: "scheduled",
    modes: ["quick", "daily", "weekly", "full"],
    dependencies: [],
    permissions: ["outbound HTTP GET to this site's own domain"],
    riskLevel: 0,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 15_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "200 + all content markers present.",
    failureCriteria: "Unreachable, non-200, or missing marker.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: runHomepageSmoke,
  },
  {
    id: "qa-software-template-smoke",
    name: "Software Template Smoke Check",
    domain: "qa",
    description: "Live-fetches one representative /software/[slug] page and asserts 200 + expected content markers.",
    singleResponsibility: "Confirm the software page template renders correctly in production.",
    inputs: ["live HTTP GET to SITE_URL", "data/software (to pick the sample page)"],
    outputs: ["Finding[] (issue) on failure only"],
    trigger: "scheduled",
    modes: ["quick", "daily", "weekly", "full"],
    dependencies: [],
    permissions: ["outbound HTTP GET to this site's own domain"],
    riskLevel: 0,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 15_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "200 + all content markers present.",
    failureCriteria: "Unreachable, non-200, or missing marker.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: runSoftwareTemplateSmoke,
  },
  {
    id: "qa-category-template-smoke",
    name: "Category Template Smoke Check",
    domain: "qa",
    description: "Live-fetches one representative /category/[slug] page and asserts 200 + expected content markers.",
    singleResponsibility: "Confirm the category page template renders correctly in production.",
    inputs: ["live HTTP GET to SITE_URL", "data/categories (to pick the sample page)"],
    outputs: ["Finding[] (issue) on failure only"],
    trigger: "scheduled",
    modes: ["quick", "daily", "weekly", "full"],
    dependencies: [],
    permissions: ["outbound HTTP GET to this site's own domain"],
    riskLevel: 0,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 15_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "200 + all content markers present.",
    failureCriteria: "Unreachable, non-200, or missing marker.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: runCategoryTemplateSmoke,
  },
  {
    id: "qa-comparison-template-smoke",
    name: "Comparison Template Smoke Check",
    domain: "qa",
    description: "Live-fetches one representative /compare/[comparison] page and asserts 200 + expected content markers.",
    singleResponsibility: "Confirm the comparison page template renders correctly in production.",
    inputs: ["live HTTP GET to SITE_URL", "data/comparisons (to pick the sample page)"],
    outputs: ["Finding[] (issue) on failure only"],
    trigger: "scheduled",
    modes: ["quick", "daily", "weekly", "full"],
    dependencies: [],
    permissions: ["outbound HTTP GET to this site's own domain"],
    riskLevel: 0,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 15_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "200 + all content markers present.",
    failureCriteria: "Unreachable, non-200, or missing marker.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: runComparisonTemplateSmoke,
  },
  {
    id: "qa-sitemap-live-validation",
    name: "Live Sitemap Validation",
    domain: "qa",
    description: "Fetches the deployed /sitemap.xml over HTTP and cross-checks its URL count against the current dataset — catches deployment/CDN drift that maint-seo's code-level check structurally cannot.",
    singleResponsibility: "Confirm the deployed sitemap matches the current dataset.",
    inputs: ["live HTTP GET to SITE_URL/sitemap.xml", "data/software, data/categories, data/comparisons"],
    outputs: ["Finding[] (issue) on failure only"],
    trigger: "scheduled",
    modes: ["daily", "weekly", "full"],
    dependencies: [],
    permissions: ["outbound HTTP GET to this site's own domain"],
    riskLevel: 0,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 15_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "200 + URL count within tolerance of the current dataset.",
    failureCriteria: "Unreachable, non-200, or URL count far below expected.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: runSitemapLiveValidation,
  },
  {
    id: "qa-robots-live-validation",
    name: "Live Robots.txt Validation",
    domain: "qa",
    description: "Fetches the deployed /robots.txt over HTTP and checks it disallows /internal/ and references the sitemap.",
    singleResponsibility: "Confirm the deployed robots.txt matches the intended policy.",
    inputs: ["live HTTP GET to SITE_URL/robots.txt"],
    outputs: ["Finding[] (issue) on failure only"],
    trigger: "scheduled",
    modes: ["daily", "weekly", "full"],
    dependencies: [],
    permissions: ["outbound HTTP GET to this site's own domain"],
    riskLevel: 0,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 15_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "200 + disallow rule + sitemap reference present.",
    failureCriteria: "Unreachable, non-200, or missing disallow rule.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: runRobotsLiveValidation,
  },
  {
    id: "qa-production-deployment-smoke",
    name: "Production Deployment Smoke Check",
    domain: "qa",
    description: "The fastest, coarsest check in the swarm: is the production origin up at all and returning real HTML.",
    singleResponsibility: "Fail fast if production itself is down.",
    inputs: ["live HTTP GET to SITE_URL"],
    outputs: ["Finding[] (issue) on failure only"],
    trigger: "scheduled",
    modes: ["quick", "daily", "weekly", "full"],
    dependencies: [],
    permissions: ["outbound HTTP GET to this site's own domain"],
    riskLevel: 0,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 15_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "200 + text/html content-type.",
    failureCriteria: "Unreachable or non-200/non-HTML.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: productionDeploymentSmokeRun,
  },
  {
    id: "qa-critical-route-availability",
    name: "Critical Route Availability",
    domain: "qa",
    description: "Checks the hand-picked core marketing/legal routes (/, /recommend, /compare, /about, /contact, /privacy, /cookies, /terms) for availability.",
    singleResponsibility: "Confirm core navigation routes are reachable.",
    inputs: ["live HTTP GET to SITE_URL"],
    outputs: ["Finding[] (issue) on failure only"],
    trigger: "scheduled",
    modes: ["quick", "daily", "weekly", "full"],
    dependencies: [],
    permissions: ["outbound HTTP GET to this site's own domain"],
    riskLevel: 0,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 20_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "All 8 routes return outcome ok.",
    failureCriteria: "Any route not ok.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: criticalRouteAvailabilityRun,
  },
  {
    id: "qa-ga4-consent-static-check",
    name: "GA4 Consent Static Check",
    domain: "qa",
    description: "Fetches the live homepage HTML and asserts the real gtag.js script never appears in server-rendered output — the one GA4-consent fact actually verifiable via plain HTTP, since every next/script in this app uses strategy=\"afterInteractive\" (client-injected, never in raw HTML) and SSR always evaluates consent as not-yet-granted. Cannot exercise the client-side grant/decline/no-duplication flow — see docs/agents-architecture.md for that coverage gap.",
    singleResponsibility: "Catch a GA4 consent-gating regression visible in server-rendered HTML.",
    inputs: ["live HTTP GET to SITE_URL"],
    outputs: ["Finding[] (regression) on failure only"],
    trigger: "scheduled",
    modes: ["quick", "daily", "weekly", "full"],
    dependencies: [],
    permissions: ["outbound HTTP GET to this site's own domain"],
    riskLevel: 0,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 15_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "No gtag.js script tag in server-rendered HTML.",
    failureCriteria: "gtag.js present in server-rendered HTML.",
    verificationAgent: "qa-ga4-consent-code-audit",
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: ga4ConsentStaticCheckRun,
  },
  {
    id: "qa-ga4-consent-code-audit",
    name: "GA4 Consent Code Audit",
    domain: "qa",
    description: "Static source check: confirms lib/consent.ts, ConsentBanner.tsx, GoogleAnalyticsConsent.tsx, and CookiePreferencesControl.tsx still exist, and Analytics.tsx's \"ga\" branch still delegates to GoogleAnalyticsConsent rather than rendering a raw gtag.js script.",
    singleResponsibility: "Catch a GA4 consent-gating regression at the source-code level.",
    inputs: ["lib/consent.ts, components/ConsentBanner.tsx, components/GoogleAnalyticsConsent.tsx, components/CookiePreferencesControl.tsx, components/Analytics.tsx"],
    outputs: ["Finding[] (regression) on failure only"],
    trigger: "scheduled",
    modes: ["quick", "daily", "weekly", "full"],
    dependencies: [],
    permissions: ["read local source files"],
    riskLevel: 0,
    costClass: "free",
    modelRequirement: "none",
    timeoutMs: 5_000,
    retryPolicy: { maxAttempts: 1, backoffMs: 0 },
    successCriteria: "All required files exist; Analytics.tsx delegates correctly.",
    failureCriteria: "A required file is missing, or Analytics.tsx no longer delegates.",
    verificationAgent: null,
    enabled: true,
    blockedReason: null,
    version: "1.0.0",
    run: ga4ConsentCodeAuditRun,
  },
];
